In [12]:
import re
import nltk
import pickle
import numpy as np
import pandas as pd
import tensorflow as tf

In [13]:
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

In [70]:
data = pd.read_csv('train.csv')

In [71]:
data

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
...,...,...,...,...,...
20795,20795,Rapper T.I.: Trump a ’Poster Child For White S...,Jerome Hudson,Rapper T. I. unloaded on black celebrities who...,0
20796,20796,"N.F.L. Playoffs: Schedule, Matchups and Odds -...",Benjamin Hoffman,When the Green Bay Packers lost to the Washing...,0
20797,20797,Macy’s Is Said to Receive Takeover Approach by...,Michael J. de la Merced and Rachel Abrams,The Macy’s of today grew from the union of sev...,0
20798,20798,"NATO, Russia To Hold Parallel Exercises In Bal...",Alex Ansary,"NATO, Russia To Hold Parallel Exercises In Bal...",1
20799,20799,What Keeps the F-35 Alive,David Swanson,"David Swanson is an author, activist, journa...",1

In [72]:
data = data.iloc[:, [1, 4]]
data.head()

                                               title  label
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1
1  FLYNN: Hillary Clinton, Big Woman on Campus - ...      0
2                  Why the Truth Might Get You Fired      1
3  15 Civilians Killed In Single US Airstrike Hav...      1
4  Iranian woman jailed for fictional unpublished...      1

In [73]:
data = data.dropna()
data

                                                   title  label
0      House Dem Aide: We Didn’t Even See Comey’s Let...      1
1      FLYNN: Hillary Clinton, Big Woman on Campus - ...      0
2                      Why the Truth Might Get You Fired      1
3      15 Civilians Killed In Single US Airstrike Hav...      1
4      Iranian woman jailed for fictional unpublished...      1
...                                                  ...    ...
20795  Rapper T.I.: Trump a ’Poster Child For White S...      0
20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...      0
20797  Macy’s Is Said to Receive Takeover Approach by...      0
20798  NATO, Russia To Hold Parallel Exercises In Bal...      1
20799                          What Keeps the F-35 Alive      1

[20242 rows x 2 columns]

In [74]:
len(data)

20242

In [75]:
stemmer = nltk.stem.PorterStemmer()
stopwords = nltk.corpus.stopwords.words('english')
def clean_data(text):
    text = re.sub('[^a-zA-Z]',' ', text)
    text = text.lower()
    text = text.split()
    text = [stemmer.stem(j) for j in text if j not in stopwords]
    text = ' '.join(text)
    return text

In [76]:
sentences = list(data['title'])
labels = list(data['label'])

In [77]:
data = []
for i in sentences:
    text = clean_data(i)
    data.append(text)

In [78]:
x = [data, labels]

In [79]:
with open('title_train_data_oh.pickle', "wb") as file:
        pickle.dump(x, file)